<?php

/**
 * File summary.
 *
 * This is the longer file description for the type rendering tests.
 *
 * @package Something
 * @since 1.0.0
 */

/**
 * This is a function summary.
 *
 * @since 1.4.0
 *
 * @param list<string|WP_Post> $x Desc.
 *
 * @return list<string|WP_Post> Ret.
 */
function wp_parser_type_rendering_generic_func( $x ) {

	/* Code would go here. */
}

/**
 * This is another function summary.
 *
 * @since 1.4.0
 *
 * @return string|int Ret.
 */
function wp_parser_type_rendering_union_func() {

	/* Code would go here. */
}

// EOF
