<?php

/**
 * File summary.
 *
 * This is the longer file description. It can be very long, and even span multiple
 * lines, if hard wrapped as it should be.
 *
 * @package Something
 * @since 1.0.0
 */

/**
 * This is a function summary.
 *
 * This function is just here for tests. This is its longer description.
 *
 * @since 1.4.0
 *
 * @param string $var A string variable which is the first parameter.
 * @param int[]  $ids An array of user IDs.
 *
 * @return mixed The return type is random. (Not really.)
 */
function wp_parser_test_func( $var, array $ids = array() ) {

	/* Code would go here. */
}

// EOF
