name: Unit Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
    test-php:
      runs-on: ubuntu-latest
      strategy:
          fail-fast: false
          matrix:
              php:
                - '7.4'

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set PHP version for wp-env
        run: echo '{"phpVersion":"${{ matrix.php }}"}' > .wp-env.override.json

      - name: Install
        run: npm install

      - name: Test
        run: npm test
