name: Unit Tests

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
    test-php:
      runs-on: ubuntu-latest
      strategy:
          fail-fast: false
          matrix:
              php:
                - '8.1'
                - '8.2'
                - '8.3'
                - '8.4'

      env:
        WP_ENV_PHP_VERSION: ${{ matrix.php }}

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Setup Environment
        run: |
          npm run setup

      - name: Test
        run: npm run test
