name: Unit Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.4"

    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install
        run: npm ci

      - name: Setup Environment
        run: |
          composer install --no-interaction --no-security-blocking
          npm run setup

      - name: Test
        run: npm run test
