name: Unit Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.4"

    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Setup test environment
        run: npm run test:phpunit:setup

      - name: Test
        run: npm run test
